export default [
    {
        index: "1",
        name: "行内元素",
        icon: "",
        child: [
            {name: "a",index: "1-1",},
            {name: "abbr",index: "1-2",},
            {name: "b",index: "1-3",},
            {name: "big",index: "1-4",},
            {name: "br",index: "1-5",},
            {name: "cite",index: "1-6",},
            {name: "acronym",index: "1-7",},
            {name: "code",index: "1-8",},
            {name: "dfn",index: "1-9",},
            {name: "em",index: "1-10",},
            {name: "font",index: "1-11",},
            {name: "i",index: "1-12",},
            {name: "img",index: "1-13",},
            {name: "imput",index: "1-14",},
            {name: "label",index: "1-15",},
            {name: "kbd",index: "1-16",},
            {name: "s",index: "1-17",},
            {name: "samp",index: "1-18"},
            {name: "select",index: "1-19"},
            {name: "small",index: "1-20"},
            {name: "span",index: "1-21"},
            {name: "strike",index: "1-22"},
            {name: "strong",index: "1-23"},
            {name: "sub",index: "1-24"},
            {name: "sup",index: "1-25"},
            {name: "textarea",index: "1-26"},
            {name: "u",index: "1-27"},
            {name: "tt",index: "1-28"},
            {name: "var",index: "1-29"},
        ]
    },
    {
        index: "2",
        name: "块级元素",
        icon: "",
        child: [
            {name:"address",index: "1-1"},
            {name:"caption",index: "1-2"},
            {name:"dd",index: "1-3"},
            {name:"div",index: "1-4"},
            {name:"dl",index: "1-5"},
            {name:"dt",index: "1-6"},
            {name:"fieldset",index: "1-7"},
            {name:"form",index: "1-8"},
            {name:"h1",index: "1-9"},
            {name:"h2",index: "1-10"},
            {name:"h3",index: "1-11"},
            {name:"h4",index: "1-12"},
            {name:"h5",index: "1-13"},
            {name:"h6",index: "1-14"},
            {name:"hr",index: "1-15"},
            {name:"legend",index: "1-16"},
            {name:"li",index: "1-17"},
            {name:"noframes",index: "1-18"},
            {name:"noscript",index: "1-19"},
            {name:"ol",index: "1-20"},
            {name:"ul",index: "1-21"},
            {name:"p",index: "1-22"},
            {name:"pre",index: "1-23"},
            {name:"table",index: "1-24"},
            {name:"tbody",index: "1-25"},
            {name:"td",index: "1-26"},
            {name:"tfoot",index: "1-27"},
            {name:"th",index: "1-28"},
            {name:"thead",index: "1-29"},
            {name:"tr",index: "1-30"},
        ]
    }
]